spring:
  profiles:
    active: dev

server:
  port: 8080

---

spring:
  profiles: dev
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/db_nomebanco?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: nomebanco
    password: senhabanco
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  profiles: test
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true